erDiagram
    auth_clients {
        int id PK
        varchar client_id UK
        varchar client_type
        boolean allow_custom_claims
        jsonb enforced_claims
        boolean is_deleted
    }

    token_policies {
        int id PK
        int auth_client_id FK
        varchar name
        int time_to_live_in_seconds
        text[] permissions
        boolean full_access
        int version
        boolean allow_tenant_header
    }

    api_keys {
        int id PK
        int auth_client_id FK
        varchar name
        varchar comment
        varchar status
        timestamptz last_rotation_utc
        timestamptz status_change_utc
    }

    trusted_issuers {
        int id PK
        varchar issuer_name UK
        text[] access_type_groups
        varchar storage_type
        varchar valid_issuer
        boolean validate_audience
        varchar discovery
        varchar jwks_url
        jsonb public_keys_json
    }

    rsa_rotations {
        int id PK
        varchar execution_step_system_name
        varchar status
        varchar trigger_source
        timestamptz created
        timestamptz completed
        int after_new_key_created_delay_count
        int before_old_key_deleted_delay_count
        varchar primary_key_hash
    }

    event_log_entries {
        int id PK
        timestamptz logged_datetime_utc
        varchar system_name
        varchar comment
        jsonb payload
        varchar client_id
        varchar staff_email
    }

    auth_clients ||--o{ token_policies : "имеет"
    auth_clients ||--o{ api_keys : "имеет"
